<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<title>My app title</title>
<head>

<?php echo $this->headLink()->appendStylesheet('/testproject/public/css/style.css') ?> 
<?php echo $this->headScript()->appendFile('/testproject/public/js/jquery-latest.js') ?>
<?php echo $this->headScript()->appendFile('/testproject/public/js/jquery.tablesorter.js') ?>
</head>
<body>
<?php echo $this->layout()->content ?>

</body>
</html>



